### ISSUE TITLE
Improve the distinction between read/unread notifications

### ISSUE THREAD

**Issue by tomS3210** [cabot/damaioconfiguration#3]
Hello Cabot,

Thank you for this very pleasant style, I use it on my site www.Ma-BMW.com/forum

I have a recurring request from members: In the notifications menu it is difficult to distinguish read/unread. Could you fix this either by changing the background color, or by adding a small vertical bar of color on the unread ones?

Thank you :-)

<img width="1238" alt="Notifications" src="https://github.com/user-attachments/assets/e966c65d-c596-4511-8f95-ac5cef550f78" />

**Comment by cabot** [comment]
Hello,

Add this to the **CSS Rules** field of the **Damaïo configuration** extension:
```css
.notification_list .dropdown-contents li {
	border-inline: 4px solid transparent;
}

.notification_list .dropdown-contents li.bg2 {
	border-inline-color: var(--main-color1);
}

.dropdown-extended ul li a, .dropdown-extended ul li.no-url {
	padding-inline: 4px;
}
```
This will add a left/right side border in the style's main colour to unread notifications.

You can replace `var(--main-color1)` with `var(--main-color2)` to display a slightly lighter colour (like the one on the link hover), or even `var(--main-color3)` to display the red colour you've selected for the button hover.

Please let me know if it suits you.
